version: "3"
services:
  my-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: node_crawlerthon-api:latest
    container_name: node_crawlerthon-api-container
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app # Mount the host folder to the container
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
    restart: always
    ports:
      - "9200:9200"
    networks:
      - my-network
    # Set memory limit and CPU limit for Elasticsearch
    mem_limit: 1GB # Limit memory
    cpus: 1 # Limit to 1 CPU core

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana-container
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - my-network
    # Set memory limit and CPU limit for Kibana
    mem_limit: 1GB # Limit memory
    cpus: 1 # Limit to 1 CPU core

networks:
  my-network:
    driver: bridge
